version: "3.5"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "postgres:/var/lib/postgresql/data"

  postgres-test:
    image: postgres
    ports:
      - "5431:5432"
    env_file:
      - .env

volumes:
  postgres:
